### PR TITLE
Update to ECS 8.4

### PR DESCRIPTION
**Pull request by lancegliser**
Providing the results of following the directions and a few required tweaks along the way for discussion.

### CODE REVIEW

**Comment by lancegliser** [comment]
I've got some concerns about the output that's generated. Take a look at things like ECSTree's code:


```ts
export interface EcsTree {
  /**
	* @timestamp
	* Docs: https://www.elastic.co/guide/en/ecs/8.4/ecs-base.html
	* Field Set: base
	* Level: core
	* Elasticsearch type: date
	* Description: Date/time when the event originated. This is the date/time extracted from the event, typically representing when the event was generated by the source.
	If the event source has no original timestamp, this value is typically populated by the first time the event was received by the pipeline.
	Required field for all events.
	* Example: 2016-05-23T08:05:34.853Z
	*/
  "@timestamp": Date;

  /**
   * file.accessed
   * Docs: https://www.elastic.co/guide/en/ecs/8.4/ecs-file.html
   * Field Set: file
   * Level: extended
   * Elasticsearch type: date
   * Description: Last time the file was accessed. Note that not all filesystems keep track of access time.
   * Example: <None>
   */
  accessed: Date;
}
```

`@timestamp` is pretty much fine. But `accessed` is actually meant to be at `file.accessed`. Seems like a fundamental flaw in its generation.

**Comment by lancegliser** [comment]
I might also suggest a change to the way the README suggests building schemas. I found this much faster to work with:

```ts
import { EcsFields } from "./ecs";

export * from "./ecs";
export * from "./schema";

/**
 * Custom fields allowed across any of our usages
 */
interface CustomFields {
  "event.extras": Record<string, unknown>;
}

/**
 * A generic custom schema with no specific requirements
 */
export interface CustomECS extends EcsFields, CustomFields {}

/**
 * A custom event schema with no specific requirements
 */
export interface CustomECSEvent extends CustomECS {
  "event.kind": NonNullable<EcsFields["event.kind"]>;
  "event.category": NonNullable<EcsFields["event.category"]>;
  "event.type": NonNullable<EcsFields["event.type"]>;
  // "event.outcome": NonNullable<EcsFields["event.outcome"]>; // Not available on things like start events
}
```

**Comment by gittyeric** [comment]
Thanks for bringing this up!  I'll take a closer look this weekend.

**Comment by gittyeric** [comment]
Hey thanks for the yell, turns out Elastic added a bunch of new field types this old lib didn't know about.  I got that fixed and the latest version of this lib is now on 8.4 :-) .  You can simply use the latest version from NPM as-is without having to build anything custom.  Let me know how it works out for you.

**Pull request closed without merging**
